version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: sudo npm install yarn -g
      - restore_cache:
          keys:
            - node-cache-{{ checksum "yarn.lock" }}-{{ .Branch }}
            - node-cache-{{ checksum "yarn.lock" }}
            - node-cache
      - run: yarn install
      - run: yarn test
      - save_cache:
          key: node-cache-{{ checksum "yarn.lock" }}-{{ .Branch }}
          paths:
            - node_modules
workflows:
  version: 2
  build_and_publish:
    jobs:
      - test
